import Head from 'next/head'
//import { client } from '@/lib/contentful/client'
import ContactPageCard from '@/components/contact/ContactPageCard';
import ContactForm from '@/components/contact/ContactForm';

const Contacts = ({ contacts }) => {
  return (
    <>
      <Head>
        <title>McFadden Design | Contact McFadden Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2db1cf" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff" />


      </Head>

        <section className='aboutPage interior'>
            <div className='theRest about contactPage'>
                <div className='inside-xxl'>
                    <h1>Contact McFadden Design</h1>
                </div>

                <section className='inside-xxl flex-md justify'>
                    <div className='fifty'>
                        {contacts.map((contact) => (
                        <ContactPageCard key={contact.slug} contact={contact} />
                        ))}
                    </div>
                    <div className='forty-five'>
                        <ContactForm />
                    </div>
                </section>

            </div>
        </section>

    </>
  )
}

export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          contactCollection {
            items {
              slug
              title
              content {
                json
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const contacts = data.contactCollection.items;

  return {
    props: {
      contacts
    }
  }

}
export default Contacts