import Head from 'next/head'
//import { client } from '@/lib/contentful/client'
import ProjectCard from '@/components/projects/ProjectCard'
import ProjectPageCard from '@/components/projects/ProjectPageCard'


const Projects = ({ mainProjects, stickyProjects }) => {
  return (
    <>
      <Head>
        <title>McFadden Design | Projects</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2db1cf" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <section className='projects interior' id='projects'>
        <div className='theRest'>
          
          {stickyProjects.map((project) => (
              <ProjectPageCard key={project.slug} project={project} />
          ))}
          
          <div className='projectMap inside-xxl'>
            <ul className='projectGrid auto-grid'>
              {mainProjects.map((project) => (
                <ProjectCard key={project.slug} project={project} />
              ))}
            </ul>
          </div>
        </div>
      </section>

    </>
  )
}

export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          stickyProject:projectCollection(where: { category: "Sticky" }, limit: 1) {
            items {
              title
              slug
              content {
                json
              }
              featuredImage {
                url
                width
                height
              }
            }
          }
          mainProject:projectCollection(where: { category_not: "Sticky" }) {
            items {
              title
              slug
              featuredImage {
                url
                width
                height
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const mainProjects = data.mainProject.items;
  const stickyProjects = data.stickyProject.items;

  return {
    props: {
      mainProjects,
      stickyProjects
    }
  }

}
export default Projects