import Head from 'next/head'
//import { client } from '@/lib/contentful/client'
import TestimonialCard from '@/components/testimonials/TestimonialCard';

const Testimonials = ({ testimonials }) => {
  return (
    <>
      <Head>
        <title>McFadden Design | Testimonials</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2db1cf" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <section className='testimonailPage interior'>
        <div className='theRest'>
          
          <section className='testimonialPage inside-xxl'>
            <h1>Testimonials</h1>
            {testimonials.map((testimonial) => (
              <TestimonialCard key={testimonial.slug} testimonial={testimonial} />
            ))}
          </section>

        </div>
      </section>

    </>
  )
}

export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          testimonialsCollection {
            items {
              title
              slug
              content {
                json
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const testimonials = data.testimonialsCollection.items;

  return {
    props: {
      testimonials
    }
  }

}
export default Testimonials