import Head from 'next/head'
//import { client } from '@/lib/contentful/client'
import AboutPageCard from '@/components/abouts/AboutPageCard';

const Abouts = ({ abouts }) => {
  return (
    <>
      <Head>
        <title>McFadden Design | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest" />
        <link rel="mask-icon" href="/safari-pinned-tab.svg" color="#2db1cf" />
        <meta name="msapplication-TileColor" content="#00aba9" />
        <meta name="theme-color" content="#ffffff" />
      </Head>

      <section className='aboutPage interior'>
        <div className='theRest'>
          
          <section className='about inside-xxl'>
            {abouts.map((about) => (
              <AboutPageCard key={about.slug} about={about} />
            ))}
          </section>

        </div>
      </section>

    </>
  )
}

export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          aboutCollection {
            items {
              slug
              title
              content {
                json
              }
              image1 {
                url
                width
                height
                description
              }
              image2 {
                url
                width
                height
                description
              }
              image3 {
                url
                width
                height
                description
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const abouts = data.aboutCollection.items;

  return {
    props: {
      abouts
    }
  }

}
export default Abouts