import Head from 'next/head'
import ContentfulImage from '@/components/ui/ContentfulImage'
import Arrow from "@/public/arrow.svg"

import Link from 'next/link'
//import Image from 'next/image'
import { Inter } from 'next/font/google'
import ProjectCardSlide from '@/components/projects/ProjectCardSlide'

import Slider from 'react-slick'
import AboutCard from '@/components/abouts/AboutCard'
import TestimonialCardSlide from '@/components/testimonials/TestimonialCardSlide'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ projects, abouts, testimonials }) {
  const settings = {
    dots: true,
    arrows: false,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };
  return (
    <>
      <Head>
        <title>McFadden Design - Architect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='home'>
        <Slider {...settings}>
          {projects.map((project) => (
            <ProjectCardSlide key={project.slug} project={project} />
          ))}
        </Slider>
        <section className='about inside-xxl'>
          {abouts.map((about) => (
            <AboutCard key={about.slug} about={about} />
          ))}
        </section>
        <section className='testimonials'>
          <Slider {...settings}>
            {testimonials.map((testimonial) => (
              <TestimonialCardSlide key={testimonial.slug} testimonial={testimonial} />
            ))}
          </Slider>
          <div className='slideLinkContainer'>
          <Link href={`/testimonials`} aria-label="Testimonials" className='slideLink always-flex'>
            <span className='words'>All Testimonials</span>
            <span className='arrow flex-vertical'>
              <ContentfulImage
                  alt='Arrow'
                  src={Arrow}
                  width='30'
                  height='100'
              />
            </span>
          </Link>
        </div>
        </section>
      </main>
    </>
  )
}


export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          testimonialsCollection(where: { category: "Home" }) {
            items {
              title
              slug
              excerpt
            }
          }
          project1:projectCollection(where: { category: "Slider" }, limit: 2) {
            items {
              title
              slug
              excerpt
              featuredImage {
                url
                width
                height
              }
            }
          }
          aboutCollection {
            items {
              slug
              title
              excerpt {
                json
              }
              image1 {
                url
                width
                height
                description
              }
              image2 {
                url
                width
                height
                description
              }
              image3 {
                url
                width
                height
                description
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const projects = data.project1.items;
  const abouts = data.aboutCollection.items;
  const testimonials = data.testimonialsCollection.items;

  return {
    props: {
      projects,
      abouts,
      testimonials
    }
  }

}
