import Head from 'next/head'
//import Image from 'next/image'
import { Inter } from 'next/font/google'
import ProjectCardSlide from '@/components/projects/ProjectCardSlide'

import Slider from 'react-slick'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ projects }) {
  const settings = {
    dots: true,
    arrows: false,
    infinite: false,
    speed: 500,
    slidesToShow: 1,
    slidesToScroll: 1
  };
  return (
    <>
      <Head>
        <title>McFadden Design - Architect</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='home'>
        
        <Slider {...settings}>
          {projects.map((project) => (
            <ProjectCardSlide key={project.slug} project={project} />
          ))}
        </Slider>
        <h1>Home</h1>
      </main>
    </>
  )
}


export async function getStaticProps() {
  const result = await fetch(`https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`, {
    method: 'POST', 
    headers: {
      Authorization: `Bearer ${process.env.CONTENTFUL_ACCESS_TOKEN}`,
      'Content-Type': 'application/JSON'
    },
    body: JSON.stringify({
      query: `
        query {
          projectCollection {
            items {
              title
              slug
              excerpt
              featuredImage {
                url
                width
                height
              }
            }
          }
        }
      `,
    })
  });

  if(!result.ok) {
    console.error(result);
    return {};
  }

  const { data } = await result.json();
  const projects = data.projectCollection.items;

  return {
    props: {
      projects
    }
  }

}
